// This code was AUTOGENERATED using the library.
// Please DO NOT EDIT THIS FILE.

package group_pointer

import (
	common "github.com/donutnomad/solana-web3/common"
	binary "github.com/gagliardetto/binary"
)

// GroupPointer Struct
// Group member pointer extension data for mints.
type GroupPointer struct {
	// Authority that can set the group address
	Authority common.PublicKey
	// Account address that holds the group
	GroupAddress common.PublicKey
}

const GROUP_POINTER_SIZE = 64

func (obj *GroupPointer) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	if err = encoder.Encode(&obj.Authority); err != nil {
		return err
	}
	if err = encoder.Encode(&obj.GroupAddress); err != nil {
		return err
	}
	return nil
}

func (obj *GroupPointer) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	if err = decoder.Decode(&obj.Authority); err != nil {
		return err
	}
	if err = decoder.Decode(&obj.GroupAddress); err != nil {
		return err
	}
	return nil
}
