package web3

const NUM_TICKS_PER_SECOND = 160

const DEFAULT_TICKS_PER_SLOT = 64

const NUM_SLOTS_PER_SECOND = NUM_TICKS_PER_SECOND / DEFAULT_TICKS_PER_SLOT

const MS_PER_SLOT = 1000 / NUM_SLOTS_PER_SECOND
